### GET /
GET http://localhost:5000

### Register a user POST AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "graeme@gmail.com",
    "password": "123123123"
}

### Login a user POST AUTH/LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "graeme@gmail.com",
    "password": "123123123"
}

### Fetch all todos GET /todos (protected)
GET http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgyMzM4MzMzLCJleHAiOjE3ODI0MjQ3MzN9.hGgegqz25SB85GDspmDyLHA3snIf6xl1m0is2xzQccw

### Create a new todo POST /todos (protected)
POST http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgyMzM4MzMzLCJleHAiOjE3ODI0MjQ3MzN9.hGgegqz25SB85GDspmDyLHA3snIf6xl1m0is2xzQccw
Content-Type: application/json

{
    "task": "Finish coding the projects"
}

### Update a todo PUT /todos/:id (protected)
PUT http://localhost:5000/todos/2?page=4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgyMzM3MDczLCJleHAiOjE3ODI0MjM0NzN9.njmIYSBp6N6XvL_6B9zjGqkiIOD_NSG83Inbd-AiewI
Content-Type: application/json

{
    "completed": 1
}

### Delete a todo DELETE /todos/:id (protected)
DELETE http://localhost:5000/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzgyMzM3MDczLCJleHAiOjE3ODI0MjM0NzN9.njmIYSBp6N6XvL_6B9zjGqkiIOD_NSG83Inbd-AiewI
Content-Type: application/json